[tool.black]
line-length = 99
exclude = '''
(
  /(
      \.github
    | \.ruff_cache
    | \.verify-helper
  )/
)
'''

[tool.ruff]
line-length = 99
ignore = [
    "E501",
    "E741",
    "E402",
    "F811"
]
exclude = [".github/"]
