name: verify

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
          python-version: 3.11

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Copy dependencies
      run: |
        rm -rf ${{ env.pythonLocation }}/lib/python$MINOR_VERSION/site-packages/onlinejudge_verify
        cp -r ./.github/oj-verify ${{ env.pythonLocation }}/lib/python3.11/site-packages/onlinejudge_verify
        sleep 5

    - name: create docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: python3 .github/oj-verify/main.py docs
